config/routes.rb
Rails.application.routes.draw do
  get "users/new", to:"users#new"
  post "users/new", to:"users#create"
  get "users", to:"users#index"
  get "users/:id/edit", to:"users#edit"
  post "users/:id", to:"users#update"
  get "users/:id", to:"users#show"

  get "login", to:"sessions#new"
  post "login", to:"sessions#create"
  delete "logout", to:"sessions#destroy"

  get "comments/:post_id/new", to:"comments#new"
  post "comments/new", to:"comments#create"
  get "comments/:id/edit", to:"comments#edit"
  post "comments/:id/update", to:"comments#update"
  delete "comments/:id", to:"comments#destroy"

  post "likes/:post_id", to:"likes#create"
  delete "likes/:id", to:"likes#destroy"

  resources :posts
  resources :relationships, only: [:create, :destroy]
end

app/models/user.rb
class User < ApplicationRecord
    mount_uploader :image, ImageUploader

    has_many :posts, dependent:   :destroy
    has_many :comments, dependent:   :destroy
    has_many :likes, dependent:   :destroy
    has_many :active_relationships, class_name:  "Relationship",
                                  foreign_key: "follower_id",
                                  dependent:   :destroy
    has_many :passive_relationships, class_name:  "Relationship",
                                   foreign_key: "followed_id",
                                   dependent:   :destroy
    has_many :following, through: :active_relationships, source: :followed
    has_many :followers, through: :passive_relationships, source: :follower
    
    before_save { self.email = email.downcase }
    validates :name, presence: true, length: {maximum: 50}
    VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i
    validates :email, presence: true, length: {maximum: 250},
                                      format: { with: VALID_EMAIL_REGEX }
    has_secure_password
    validates :password, presence: true, length: {minimum: 6}, allow_nil: true

    # 渡された文字列のハッシュ値を返す
    def User.digest(string)
        cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
                                                    BCrypt::Engine.cost
        BCrypt::Password.create(string, cost: cost)
    end

    def follow(other_user)
        following << other_user unless self == other_user
    end

    def unfollow(other_user)
        following.delete(other_user)
    end

    def following?(other_user)
        following.include?(other_user)
    end

    # これがないとユーザーの検索ができなくなる
    def self.ransackable_attributes(auth_object = nil)
        ["created_at", "email", "id", "name", "password_digest", "updated_at"]
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    before_action :can_login_user, only:[:index, :show]
    before_action :edit_user_only_login_user, only:[:edit, :update]
    before_action :not_login_user, only: [:new, :create]

    def index
        @q = User.ransack(params[:q])
        @users = @q.result.order("created_at desc")
    end

    def new
        @user = User.new
    end

    def create
        @user = User.new(name: params[:name],
                         email: params[:email],
                         password: params[:password],
                         image: params[:image])
        if @user.save
            login @user
            redirect_to posts_path, notice: "新規登録に成功しました。"
        else
            render 'new', status: :unprocessable_entity
        end
    end

    def edit
    end

    def update
        if @user.update(name: params[:name], email: params[:email])
            redirect_to "/users/#{@user.id}", notice: "ユーザー情報を更新しました。"
        else
            render 'edit', status: :unprocessable_entity
        end
    end

    def show
        @user = User.find(params[:id])
        @posts = Post.where(user_id: @user.id)
    end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_follow.html.erb
<%= form_with(model: current_user.active_relationships.build) do |f| %>
  <div><%= hidden_field_tag :followed_id, @user.id %></div>
  <%= f.submit "Follow", class: "btn btn-primary" %>
<% end %>

app/views/users/_follow_form.html.erb
<% unless current_user?(@user) %>
  <div class="follow_form_div">
    <div id="follow_form">
    <% if current_user.following?(@user) %>
      <%= render 'unfollow' %>
    <% else %>
      <%= render 'follow' %>
    <% end %>
    </div>
  </div>
<% end %>

app/views/users/_unfollow.html.erb
<%= form_with(model: current_user.active_relationships.find_by(followed: @user),
              html: { method: :delete }) do |f| %>
  <%= f.submit "Unfollow", class: "btn btn-secondary" %>
<% end %>

app/views/users/edit.html.erb
<%= render 'shared/form_common', title: 'ユーザー編集画面' %>

    <div class="form-width">
        <%= form_with(url: "/users/#{@user.id}", method: "post") do |f| %>
            <%= render 'shared/error_messages' %>

            <%= f.label :name, "名前" %><br>
            <%= f.text_field :name, value: @user.name, class: 'form-control' %><br><br>

            <%= f.label :email, "メールアドレス" %><br>
            <%= f.email_field :email, value: @user.email, class: 'form-control' %><br><br>

            <%= f.submit "決定", class: "btn btn-primary" %>
            <div class="mt-3">
                <button type="button" class="btn btn-secondary" onclick="history.back();">戻る</button>
            </div>
        <% end %>
    </div>
</div>

app/views/users/index.html.erb
<%# フォームと一緒なので、仕方なくindexはform_commonを使っている　%>
<%= render 'shared/form_common', title: 'ユーザー一覧画面' %>

    <div class="form-width mb-5 mt-2">
        <%= search_form_for @q do |f| %>

        <div class="mt-3">
            <%= f.label :name_cont, "投稿検索" %>
            <%= f.search_field :name_cont, class: 'form-control', placeholder: '検索ワード' %>

            <%= f.submit "検索", class: "btn btn-primary mt-3", style: "width:60px;" %>
            <%= link_to("クリア", "/users", class: "btn btn-secondary ms-2 mt-3") %>
        </div>
        <% end %>
    </div>

    <div class="user-index">
        <% @users.each do |user| %>
        <div class="user-index-flex">
            <div>
                <%= image_tag user.image.thumb.url %>
                <%= link_to(user.name,"/users/#{user.id}", class: "link") %>
            </div>
            <div class="ms-3 mt-3 mb-3">
                <strong id="followers" class="stat">
                <%= user.followers.count %>
                <span>followers</span>
                </strong>
            </div>
        </div>
        <% end %>
        <div class="text-center">
                <%= link_to("投稿一覧", posts_path, class: "btn btn-success") %>
                <button type="button" class="btn btn-secondary" onclick="history.back();">戻る</button>
        </div>
    </div>
</div>

app/views/users/new.html.erb
<%= render 'shared/form_common', title: 'サインアップ' %>

    <div class="form-width">
        <%= form_with(url: "/users/new", method: "post", multipart: true) do |f| %>
            <%= render 'shared/error_messages' %>

            <%= f.label :name, "名前" %><br>
            <%= f.text_field :name, class: 'form-control' %><br><br>

            <%= f.label :email, "メールアドレス" %><br>
            <%= f.email_field :email, class: 'form-control' %><br><br>

            <%= f.label :password, "パスワード" %><br>
            <%= f.password_field :password, class: 'form-control' %><br><br>

            <%= f.label :image, "画像" %><br>
            <%= f.file_field :image, class:'form-control', accept: 'image/*' %><br><br>
            <%= f.hidden_field :user_image_cache %>

            <%= f.submit "決定", class: "btn btn-primary" %>
        <% end %>
    </div>
</div>

app/views/users/show.html.erb
<% provide(:title, 'ユーザー詳細') %>
<div class="container">
    <div class="text-center">
        <h1>ユーザー詳細</h1>

        <%= image_tag @user.image.url, size: '150x150' %>
        <h3 class="mt-3"><%= @user.name %></h3>
        <p><%= @user.email %></p>

        <div class="follow-relations">
            <div>
                <section class="stats">
                    <%= render 'shared/stats' %>
                </section>
            </div>

            <div class="follow-btn mt-2">
                <%= render 'follow_form' if logged_in? %>
            </div>
        </div>

        <div class="mt-3">
            <button type="button" class="btn btn-secondary" onclick="history.back();">戻る</button>
            <% if @user.id == current_user.id %>
                <%= link_to("編集","/users/#{@user.id}/edit", class: "btn btn-primary ms-3") %>
            <% end %>
        </div>

    </div>
        <% @posts.each do |post| %>
            <div class="posts-list mt-3 mb-3">
                <h3 class="m-3"><%= link_to(post.title, post_path(post), class: "link") %></h3>
                <p class="ms-3 me-3"><%= post.content %></p>

                <% if comments = Comment.where(post_id: post.id) %>
                <% comments.each do |comment| %>
                    <% user = User.find_by(id: comment.user_id) %>
                    <div class="comment-body">
                        <div class="comment-content">
                            <p class="ms-3 me-3 image-circle"><i class="fa-solid fa-comment"></i><%= image_tag user.image.thumb.url, class: "ms-3" %> <%= link_to(user.name,"/users/#{user.id}", class: "link") %> : <%= comment.comment %></p>
                        </div>
                        <% if current_user.id == comment.user_id %>
                            <div class="comment-link mt-2">
                                <%= link_to("編集","/comments/#{comment.id}/edit", class: "link ms-4 me-2") %>
                                <%= link_to("削除","/comments/#{comment.id}", data: { turbo_method: :delete }, class: "link") %>
                            </div>
                        <% end %>
                    </div>
                <% end %>
                <% end %>

                <% user = User.find_by(id: post.user_id) %>
                <div class="text-end me-3">
                    <div class="mb-3">
                        <%= link_to("コメントする", "/comments/#{post.id}/new",class: "btn btn-warning ms-3") %>
                    </div>
                    </div>
                </div>
            </div>
        <% end %>
</div>