config/routes.rb
Rails.application.routes.draw do
  get "users/new", to:"users#new"
  post "users/new", to:"users#create"
  get "users", to:"users#index"
  get "users/:id/edit", to:"users#edit"
  post "users/:id", to:"users#update"
  get "users/:id", to:"users#show"

  get "login", to:"sessions#new"
  post "login", to:"sessions#create"
  delete "logout", to:"sessions#destroy"

  get "comments/:post_id/new", to:"comments#new"
  post "comments/new", to:"comments#create"
  get "comments/:id/edit", to:"comments#edit"
  post "comments/:id/update", to:"comments#update"
  delete "comments/:id", to:"comments#destroy"

  post "likes/:post_id", to:"likes#create"
  delete "likes/:id", to:"likes#destroy"

  resources :posts
  resources :relationships, only: [:create, :destroy]
end

app/views/shared/_error_comment_messages.html.erb
<% if @comment.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      <%= @comment.errors.count %>件のエラーがあります。
    </div>
    <ul>
    <% @comment.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_error_messages.html.erb
<% if @user.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      <%= @user.errors.count %>件のエラーがあります。
    </div>
    <ul>
    <% @user.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_error_post_messages.html.erb
<% if @post.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      <%= @post.errors.count %>件のエラーがあります。
    </div>
    <ul>
    <% @post.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_form_common.html.erb
<% provide(:title, title) %>
<div class="container">
    <div class="text-center">
        <h1><%= title %></h1>
    </div>

app/views/shared/_header.html.erb
<header>
    <div class="container">
        <div class="header-title">
            <%= link_to("掲示板アプリ", posts_path, class: "link") %>
        </div>

        <div class="header-nav">
            <nav>
            <% if logged_in? %>
                <li><%= link_to(current_user.name,"/users/#{current_user.id}", class: "link") %></li>
                <li><%= link_to("ユーザー一覧","/users", class: "link") %></li>
                <li><%= link_to("ログアウト", logout_path, data: { turbo_method: :delete }, class: "link") %></li>
            <% else %>
                <li><%= link_to("ログイン", login_path, class: "link") %></li>
                <li><%= link_to("サインアップ", users_new_path, class: "link") %></li>
            <% end %>
            </nav>
        </div>
    </div>
</header>
<% unless flash.empty? %>
<div class="flash-body">
    <p class="flash-content text-center"><%= flash[:notice] %></p>
</div>
<% end %>

app/views/shared/_stats.html.erb
<% @user ||= current_user %>
<div class="stats">
    <div class="mb-3">
        <strong id="following" class="stat">
        <%= @user.following.count %>
        </strong>
        <span>following</span>
    </div>

    <div class="ms-3 mb-3">
        <strong id="followers" class="stat">
        <%= @user.followers.count %>
        </strong>
        <span>followers</span>
    </div>
</div>